/* tslint:disable */
/* eslint-disable */
/**
 * OPENCOURIER-API
 * OpenCourier Backend API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CourierUpdateAdminInput
 */
export interface CourierUpdateAdminInput {
    /**
     * 
     * @type {string}
     * @memberof CourierUpdateAdminInput
     */
    firstName: string;
    /**
     * 
     * @type {string}
     * @memberof CourierUpdateAdminInput
     */
    lastName: string;
    /**
     * 
     * @type {string}
     * @memberof CourierUpdateAdminInput
     */
    node_uri?: string;
    /**
     * 
     * @type {string}
     * @memberof CourierUpdateAdminInput
     */
    phoneNumber?: string;
    /**
     * 
     * @type {string}
     * @memberof CourierUpdateAdminInput
     */
    status?: CourierUpdateAdminInputStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof CourierUpdateAdminInput
     */
    deliverySetting?: CourierUpdateAdminInputDeliverySettingEnum;
    /**
     * 
     * @type {string}
     * @memberof CourierUpdateAdminInput
     */
    stripeAccountId?: string;
    /**
     * 
     * @type {string}
     * @memberof CourierUpdateAdminInput
     */
    stripeAccountStatus?: CourierUpdateAdminInputStripeAccountStatusEnum;
}


/**
 * @export
 */
export const CourierUpdateAdminInputStatusEnum = {
    Online: 'ONLINE',
    Offline: 'OFFLINE',
    LastCall: 'LAST_CALL'
} as const;
export type CourierUpdateAdminInputStatusEnum = typeof CourierUpdateAdminInputStatusEnum[keyof typeof CourierUpdateAdminInputStatusEnum];

/**
 * @export
 */
export const CourierUpdateAdminInputDeliverySettingEnum = {
    AutoAccept: 'AUTO_ACCEPT',
    AutoReject: 'AUTO_REJECT',
    Manual: 'MANUAL',
    None: 'NONE'
} as const;
export type CourierUpdateAdminInputDeliverySettingEnum = typeof CourierUpdateAdminInputDeliverySettingEnum[keyof typeof CourierUpdateAdminInputDeliverySettingEnum];

/**
 * @export
 */
export const CourierUpdateAdminInputStripeAccountStatusEnum = {
    Complete: 'COMPLETE',
    Enabled: 'ENABLED',
    Pending: 'PENDING',
    Rejected: 'REJECTED',
    Restricted: 'RESTRICTED',
    AttentionNeeded: 'ATTENTION_NEEDED'
} as const;
export type CourierUpdateAdminInputStripeAccountStatusEnum = typeof CourierUpdateAdminInputStripeAccountStatusEnum[keyof typeof CourierUpdateAdminInputStripeAccountStatusEnum];


/**
 * Check if a given object implements the CourierUpdateAdminInput interface.
 */
export function instanceOfCourierUpdateAdminInput(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "firstName" in value;
    isInstance = isInstance && "lastName" in value;

    return isInstance;
}

export function CourierUpdateAdminInputFromJSON(json: any): CourierUpdateAdminInput {
    return CourierUpdateAdminInputFromJSONTyped(json, false);
}

export function CourierUpdateAdminInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): CourierUpdateAdminInput {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'firstName': json['firstName'],
        'lastName': json['lastName'],
        'node_uri': !exists(json, 'node_uri') ? undefined : json['node_uri'],
        'phoneNumber': !exists(json, 'phoneNumber') ? undefined : json['phoneNumber'],
        'status': !exists(json, 'status') ? undefined : json['status'],
        'deliverySetting': !exists(json, 'deliverySetting') ? undefined : json['deliverySetting'],
        'stripeAccountId': !exists(json, 'stripeAccountId') ? undefined : json['stripeAccountId'],
        'stripeAccountStatus': !exists(json, 'stripeAccountStatus') ? undefined : json['stripeAccountStatus'],
    };
}

export function CourierUpdateAdminInputToJSON(value?: CourierUpdateAdminInput | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'firstName': value.firstName,
        'lastName': value.lastName,
        'node_uri': value.node_uri,
        'phoneNumber': value.phoneNumber,
        'status': value.status,
        'deliverySetting': value.deliverySetting,
        'stripeAccountId': value.stripeAccountId,
        'stripeAccountStatus': value.stripeAccountStatus,
    };
}

