/* tslint:disable */
/* eslint-disable */
/**
 * OPENCOURIER-API
 * OpenCourier Backend API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CourierAdminDto
 */
export interface CourierAdminDto {
    /**
     * 
     * @type {string}
     * @memberof CourierAdminDto
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof CourierAdminDto
     */
    node_uri: string | null;
    /**
     * 
     * @type {string}
     * @memberof CourierAdminDto
     */
    firstName: string;
    /**
     * 
     * @type {string}
     * @memberof CourierAdminDto
     */
    lastName: string;
    /**
     * 
     * @type {string}
     * @memberof CourierAdminDto
     */
    phoneNumber: string | null;
    /**
     * 
     * @type {string}
     * @memberof CourierAdminDto
     */
    status: CourierAdminDtoStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof CourierAdminDto
     */
    deliverySetting: CourierAdminDtoDeliverySettingEnum;
    /**
     * 
     * @type {string}
     * @memberof CourierAdminDto
     */
    userId: string;
    /**
     * 
     * @type {Date}
     * @memberof CourierAdminDto
     */
    createdAt: Date;
}


/**
 * @export
 */
export const CourierAdminDtoStatusEnum = {
    Online: 'ONLINE',
    Offline: 'OFFLINE',
    LastCall: 'LAST_CALL'
} as const;
export type CourierAdminDtoStatusEnum = typeof CourierAdminDtoStatusEnum[keyof typeof CourierAdminDtoStatusEnum];

/**
 * @export
 */
export const CourierAdminDtoDeliverySettingEnum = {
    AutoAccept: 'AUTO_ACCEPT',
    AutoReject: 'AUTO_REJECT',
    Manual: 'MANUAL',
    None: 'NONE'
} as const;
export type CourierAdminDtoDeliverySettingEnum = typeof CourierAdminDtoDeliverySettingEnum[keyof typeof CourierAdminDtoDeliverySettingEnum];


/**
 * Check if a given object implements the CourierAdminDto interface.
 */
export function instanceOfCourierAdminDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "node_uri" in value;
    isInstance = isInstance && "firstName" in value;
    isInstance = isInstance && "lastName" in value;
    isInstance = isInstance && "phoneNumber" in value;
    isInstance = isInstance && "status" in value;
    isInstance = isInstance && "deliverySetting" in value;
    isInstance = isInstance && "userId" in value;
    isInstance = isInstance && "createdAt" in value;

    return isInstance;
}

export function CourierAdminDtoFromJSON(json: any): CourierAdminDto {
    return CourierAdminDtoFromJSONTyped(json, false);
}

export function CourierAdminDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CourierAdminDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'node_uri': json['node_uri'],
        'firstName': json['firstName'],
        'lastName': json['lastName'],
        'phoneNumber': json['phoneNumber'],
        'status': json['status'],
        'deliverySetting': json['deliverySetting'],
        'userId': json['userId'],
        'createdAt': (new Date(json['createdAt'])),
    };
}

export function CourierAdminDtoToJSON(value?: CourierAdminDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'node_uri': value.node_uri,
        'firstName': value.firstName,
        'lastName': value.lastName,
        'phoneNumber': value.phoneNumber,
        'status': value.status,
        'deliverySetting': value.deliverySetting,
        'userId': value.userId,
        'createdAt': (value.createdAt.toISOString()),
    };
}

