/* tslint:disable */
/* eslint-disable */
/**
 * OPENCOURIER-API
 * OpenCourier Backend API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CourierSettingUpdateAdminInput
 */
export interface CourierSettingUpdateAdminInput {
    /**
     * 
     * @type {string}
     * @memberof CourierSettingUpdateAdminInput
     */
    vehicleType?: CourierSettingUpdateAdminInputVehicleTypeEnum;
    /**
     * 
     * @type {Array<string>}
     * @memberof CourierSettingUpdateAdminInput
     */
    preferredAreas?: Array<string>;
    /**
     * 
     * @type {object}
     * @memberof CourierSettingUpdateAdminInput
     */
    shiftAvailability?: object;
    /**
     * 
     * @type {Array<string>}
     * @memberof CourierSettingUpdateAdminInput
     */
    deliveryPreferences?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof CourierSettingUpdateAdminInput
     */
    foodPreferences?: Array<string>;
    /**
     * 
     * @type {object}
     * @memberof CourierSettingUpdateAdminInput
     */
    earningGoals?: object;
    /**
     * 
     * @type {string}
     * @memberof CourierSettingUpdateAdminInput
     */
    deliverySpeed?: CourierSettingUpdateAdminInputDeliverySpeedEnum;
    /**
     * 
     * @type {Array<string>}
     * @memberof CourierSettingUpdateAdminInput
     */
    restaurantTypes?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof CourierSettingUpdateAdminInput
     */
    cuisineTypes?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof CourierSettingUpdateAdminInput
     */
    preferredRestaurantPartners?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof CourierSettingUpdateAdminInput
     */
    dietaryRestrictions?: Array<string>;
    /**
     * 
     * @type {object}
     * @memberof CourierSettingUpdateAdminInput
     */
    payRate?: object;
}


/**
 * @export
 */
export const CourierSettingUpdateAdminInputVehicleTypeEnum = {
    Bicycle: 'BICYCLE',
    Motorcycle: 'MOTORCYCLE',
    Car: 'CAR',
    Scooter: 'SCOOTER',
    OnFoot: 'ON_FOOT'
} as const;
export type CourierSettingUpdateAdminInputVehicleTypeEnum = typeof CourierSettingUpdateAdminInputVehicleTypeEnum[keyof typeof CourierSettingUpdateAdminInputVehicleTypeEnum];

/**
 * @export
 */
export const CourierSettingUpdateAdminInputDeliverySpeedEnum = {
    Regular: 'REGULAR',
    Rush: 'RUSH'
} as const;
export type CourierSettingUpdateAdminInputDeliverySpeedEnum = typeof CourierSettingUpdateAdminInputDeliverySpeedEnum[keyof typeof CourierSettingUpdateAdminInputDeliverySpeedEnum];


/**
 * Check if a given object implements the CourierSettingUpdateAdminInput interface.
 */
export function instanceOfCourierSettingUpdateAdminInput(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CourierSettingUpdateAdminInputFromJSON(json: any): CourierSettingUpdateAdminInput {
    return CourierSettingUpdateAdminInputFromJSONTyped(json, false);
}

export function CourierSettingUpdateAdminInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): CourierSettingUpdateAdminInput {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'vehicleType': !exists(json, 'vehicleType') ? undefined : json['vehicleType'],
        'preferredAreas': !exists(json, 'preferredAreas') ? undefined : json['preferredAreas'],
        'shiftAvailability': !exists(json, 'shiftAvailability') ? undefined : json['shiftAvailability'],
        'deliveryPreferences': !exists(json, 'deliveryPreferences') ? undefined : json['deliveryPreferences'],
        'foodPreferences': !exists(json, 'foodPreferences') ? undefined : json['foodPreferences'],
        'earningGoals': !exists(json, 'earningGoals') ? undefined : json['earningGoals'],
        'deliverySpeed': !exists(json, 'deliverySpeed') ? undefined : json['deliverySpeed'],
        'restaurantTypes': !exists(json, 'restaurantTypes') ? undefined : json['restaurantTypes'],
        'cuisineTypes': !exists(json, 'cuisineTypes') ? undefined : json['cuisineTypes'],
        'preferredRestaurantPartners': !exists(json, 'preferredRestaurantPartners') ? undefined : json['preferredRestaurantPartners'],
        'dietaryRestrictions': !exists(json, 'dietaryRestrictions') ? undefined : json['dietaryRestrictions'],
        'payRate': !exists(json, 'payRate') ? undefined : json['payRate'],
    };
}

export function CourierSettingUpdateAdminInputToJSON(value?: CourierSettingUpdateAdminInput | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'vehicleType': value.vehicleType,
        'preferredAreas': value.preferredAreas,
        'shiftAvailability': value.shiftAvailability,
        'deliveryPreferences': value.deliveryPreferences,
        'foodPreferences': value.foodPreferences,
        'earningGoals': value.earningGoals,
        'deliverySpeed': value.deliverySpeed,
        'restaurantTypes': value.restaurantTypes,
        'cuisineTypes': value.cuisineTypes,
        'preferredRestaurantPartners': value.preferredRestaurantPartners,
        'dietaryRestrictions': value.dietaryRestrictions,
        'payRate': value.payRate,
    };
}

