/* tslint:disable */
/* eslint-disable */
/**
 * OPENCOURIER-API
 * OpenCourier Backend API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CourierAdminDto } from './CourierAdminDto';
import {
    CourierAdminDtoFromJSON,
    CourierAdminDtoFromJSONTyped,
    CourierAdminDtoToJSON,
} from './CourierAdminDto';
import type { PaginationDto } from './PaginationDto';
import {
    PaginationDtoFromJSON,
    PaginationDtoFromJSONTyped,
    PaginationDtoToJSON,
} from './PaginationDto';

/**
 * 
 * @export
 * @interface CourierPaginatedAdminDto
 */
export interface CourierPaginatedAdminDto {
    /**
     * 
     * @type {Array<CourierAdminDto>}
     * @memberof CourierPaginatedAdminDto
     */
    data: Array<CourierAdminDto>;
    /**
     * 
     * @type {PaginationDto}
     * @memberof CourierPaginatedAdminDto
     */
    pagination?: PaginationDto;
}

/**
 * Check if a given object implements the CourierPaginatedAdminDto interface.
 */
export function instanceOfCourierPaginatedAdminDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;

    return isInstance;
}

export function CourierPaginatedAdminDtoFromJSON(json: any): CourierPaginatedAdminDto {
    return CourierPaginatedAdminDtoFromJSONTyped(json, false);
}

export function CourierPaginatedAdminDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CourierPaginatedAdminDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(CourierAdminDtoFromJSON)),
        'pagination': !exists(json, 'pagination') ? undefined : PaginationDtoFromJSON(json['pagination']),
    };
}

export function CourierPaginatedAdminDtoToJSON(value?: CourierPaginatedAdminDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': ((value.data as Array<any>).map(CourierAdminDtoToJSON)),
        'pagination': PaginationDtoToJSON(value.pagination),
    };
}

