/* tslint:disable */
/* eslint-disable */
/**
 * OPENCOURIER-API
 * OpenCourier Backend API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DeliverySubmitEventAdminInput
 */
export interface DeliverySubmitEventAdminInput {
    /**
     * 
     * @type {string}
     * @memberof DeliverySubmitEventAdminInput
     */
    deliveryId: string;
    /**
     * 
     * @type {string}
     * @memberof DeliverySubmitEventAdminInput
     */
    eventType: DeliverySubmitEventAdminInputEventTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof DeliverySubmitEventAdminInput
     */
    prepareTimeEstimate?: string | null;
}


/**
 * @export
 */
export const DeliverySubmitEventAdminInputEventTypeEnum = {
    Created: 'CREATED',
    Confirmed: 'CONFIRMED',
    Accepted: 'ACCEPTED',
    Rejected: 'REJECTED',
    Dispatched: 'DISPATCHED',
    Canceled: 'CANCELED',
    Fulfilled: 'FULFILLED',
    PickedUp: 'PICKED_UP',
    ArrivedAtPickupLocation: 'ARRIVED_AT_PICKUP_LOCATION',
    DroppedOff: 'DROPPED_OFF',
    ArrivedAtDropoffLocation: 'ARRIVED_AT_DROPOFF_LOCATION',
    Failed: 'FAILED'
} as const;
export type DeliverySubmitEventAdminInputEventTypeEnum = typeof DeliverySubmitEventAdminInputEventTypeEnum[keyof typeof DeliverySubmitEventAdminInputEventTypeEnum];


/**
 * Check if a given object implements the DeliverySubmitEventAdminInput interface.
 */
export function instanceOfDeliverySubmitEventAdminInput(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "deliveryId" in value;
    isInstance = isInstance && "eventType" in value;

    return isInstance;
}

export function DeliverySubmitEventAdminInputFromJSON(json: any): DeliverySubmitEventAdminInput {
    return DeliverySubmitEventAdminInputFromJSONTyped(json, false);
}

export function DeliverySubmitEventAdminInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeliverySubmitEventAdminInput {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'deliveryId': json['deliveryId'],
        'eventType': json['eventType'],
        'prepareTimeEstimate': !exists(json, 'prepareTimeEstimate') ? undefined : json['prepareTimeEstimate'],
    };
}

export function DeliverySubmitEventAdminInputToJSON(value?: DeliverySubmitEventAdminInput | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'deliveryId': value.deliveryId,
        'eventType': value.eventType,
        'prepareTimeEstimate': value.prepareTimeEstimate,
    };
}

