/* tslint:disable */
/* eslint-disable */
/**
 * OPENCOURIER-API
 * OpenCourier Backend API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { DeliveryAdminDto } from './DeliveryAdminDto';
import {
    DeliveryAdminDtoFromJSON,
    DeliveryAdminDtoFromJSONTyped,
    DeliveryAdminDtoToJSON,
} from './DeliveryAdminDto';
import type { PaginationDto } from './PaginationDto';
import {
    PaginationDtoFromJSON,
    PaginationDtoFromJSONTyped,
    PaginationDtoToJSON,
} from './PaginationDto';

/**
 * 
 * @export
 * @interface DeliveryAdminPaginatedDto
 */
export interface DeliveryAdminPaginatedDto {
    /**
     * 
     * @type {Array<DeliveryAdminDto>}
     * @memberof DeliveryAdminPaginatedDto
     */
    data: Array<DeliveryAdminDto>;
    /**
     * 
     * @type {PaginationDto}
     * @memberof DeliveryAdminPaginatedDto
     */
    pagination?: PaginationDto;
}

/**
 * Check if a given object implements the DeliveryAdminPaginatedDto interface.
 */
export function instanceOfDeliveryAdminPaginatedDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;

    return isInstance;
}

export function DeliveryAdminPaginatedDtoFromJSON(json: any): DeliveryAdminPaginatedDto {
    return DeliveryAdminPaginatedDtoFromJSONTyped(json, false);
}

export function DeliveryAdminPaginatedDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeliveryAdminPaginatedDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(DeliveryAdminDtoFromJSON)),
        'pagination': !exists(json, 'pagination') ? undefined : PaginationDtoFromJSON(json['pagination']),
    };
}

export function DeliveryAdminPaginatedDtoToJSON(value?: DeliveryAdminPaginatedDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': ((value.data as Array<any>).map(DeliveryAdminDtoToJSON)),
        'pagination': PaginationDtoToJSON(value.pagination),
    };
}

