/* tslint:disable */
/* eslint-disable */
/**
 * OPENCOURIER-API
 * OpenCourier Backend API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EmailLoginAdminInput
 */
export interface EmailLoginAdminInput {
    /**
     * 
     * @type {string}
     * @memberof EmailLoginAdminInput
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof EmailLoginAdminInput
     */
    password: string;
}

/**
 * Check if a given object implements the EmailLoginAdminInput interface.
 */
export function instanceOfEmailLoginAdminInput(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "email" in value;
    isInstance = isInstance && "password" in value;

    return isInstance;
}

export function EmailLoginAdminInputFromJSON(json: any): EmailLoginAdminInput {
    return EmailLoginAdminInputFromJSONTyped(json, false);
}

export function EmailLoginAdminInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmailLoginAdminInput {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'email': json['email'],
        'password': json['password'],
    };
}

export function EmailLoginAdminInputToJSON(value?: EmailLoginAdminInput | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'email': value.email,
        'password': value.password,
    };
}

