/* tslint:disable */
/* eslint-disable */
/**
 * OPENCOURIER-API
 * OpenCourier Backend API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LocationFindManyAdminArgs
 */
export interface LocationFindManyAdminArgs {
    /**
     * 
     * @type {number}
     * @memberof LocationFindManyAdminArgs
     */
    page?: number;
    /**
     * 
     * @type {number}
     * @memberof LocationFindManyAdminArgs
     */
    perPage?: number;
}

/**
 * Check if a given object implements the LocationFindManyAdminArgs interface.
 */
export function instanceOfLocationFindManyAdminArgs(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function LocationFindManyAdminArgsFromJSON(json: any): LocationFindManyAdminArgs {
    return LocationFindManyAdminArgsFromJSONTyped(json, false);
}

export function LocationFindManyAdminArgsFromJSONTyped(json: any, ignoreDiscriminator: boolean): LocationFindManyAdminArgs {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'page': !exists(json, 'page') ? undefined : json['page'],
        'perPage': !exists(json, 'perPage') ? undefined : json['perPage'],
    };
}

export function LocationFindManyAdminArgsToJSON(value?: LocationFindManyAdminArgs | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'page': value.page,
        'perPage': value.perPage,
    };
}

