/* tslint:disable */
/* eslint-disable */
/**
 * OPENCOURIER-API
 * OpenCourier Backend API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { LocationAdminDto } from './LocationAdminDto';
import {
    LocationAdminDtoFromJSON,
    LocationAdminDtoFromJSONTyped,
    LocationAdminDtoToJSON,
} from './LocationAdminDto';
import type { PaginationDto } from './PaginationDto';
import {
    PaginationDtoFromJSON,
    PaginationDtoFromJSONTyped,
    PaginationDtoToJSON,
} from './PaginationDto';

/**
 * 
 * @export
 * @interface LocationAdminPaginatedDto
 */
export interface LocationAdminPaginatedDto {
    /**
     * 
     * @type {Array<LocationAdminDto>}
     * @memberof LocationAdminPaginatedDto
     */
    data: Array<LocationAdminDto>;
    /**
     * 
     * @type {PaginationDto}
     * @memberof LocationAdminPaginatedDto
     */
    pagination?: PaginationDto;
}

/**
 * Check if a given object implements the LocationAdminPaginatedDto interface.
 */
export function instanceOfLocationAdminPaginatedDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;

    return isInstance;
}

export function LocationAdminPaginatedDtoFromJSON(json: any): LocationAdminPaginatedDto {
    return LocationAdminPaginatedDtoFromJSONTyped(json, false);
}

export function LocationAdminPaginatedDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): LocationAdminPaginatedDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(LocationAdminDtoFromJSON)),
        'pagination': !exists(json, 'pagination') ? undefined : PaginationDtoFromJSON(json['pagination']),
    };
}

export function LocationAdminPaginatedDtoToJSON(value?: LocationAdminPaginatedDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': ((value.data as Array<any>).map(LocationAdminDtoToJSON)),
        'pagination': PaginationDtoToJSON(value.pagination),
    };
}

