/* tslint:disable */
/* eslint-disable */
/**
 * OPENCOURIER-API
 * OpenCourier Backend API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PaginationDto
 */
export interface PaginationDto {
    /**
     * 
     * @type {number}
     * @memberof PaginationDto
     */
    perPage: number;
    /**
     * 
     * @type {number}
     * @memberof PaginationDto
     */
    totalItems: number;
    /**
     * 
     * @type {number}
     * @memberof PaginationDto
     */
    totalPages: number;
    /**
     * 
     * @type {number}
     * @memberof PaginationDto
     */
    currentItems: number;
    /**
     * 
     * @type {number}
     * @memberof PaginationDto
     */
    currentPage: number;
    /**
     * 
     * @type {number}
     * @memberof PaginationDto
     */
    prevPage: number | null;
    /**
     * 
     * @type {number}
     * @memberof PaginationDto
     */
    nextPage: number | null;
}

/**
 * Check if a given object implements the PaginationDto interface.
 */
export function instanceOfPaginationDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "perPage" in value;
    isInstance = isInstance && "totalItems" in value;
    isInstance = isInstance && "totalPages" in value;
    isInstance = isInstance && "currentItems" in value;
    isInstance = isInstance && "currentPage" in value;
    isInstance = isInstance && "prevPage" in value;
    isInstance = isInstance && "nextPage" in value;

    return isInstance;
}

export function PaginationDtoFromJSON(json: any): PaginationDto {
    return PaginationDtoFromJSONTyped(json, false);
}

export function PaginationDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginationDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'perPage': json['perPage'],
        'totalItems': json['totalItems'],
        'totalPages': json['totalPages'],
        'currentItems': json['currentItems'],
        'currentPage': json['currentPage'],
        'prevPage': json['prevPage'],
        'nextPage': json['nextPage'],
    };
}

export function PaginationDtoToJSON(value?: PaginationDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'perPage': value.perPage,
        'totalItems': value.totalItems,
        'totalPages': value.totalPages,
        'currentItems': value.currentItems,
        'currentPage': value.currentPage,
        'prevPage': value.prevPage,
        'nextPage': value.nextPage,
    };
}

