/* tslint:disable */
/* eslint-disable */
/**
 * OPENCOURIER-API
 * OpenCourier Backend API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserSessionAdminDto
 */
export interface UserSessionAdminDto {
    /**
     * 
     * @type {string}
     * @memberof UserSessionAdminDto
     */
    accessToken: string;
    /**
     * 
     * @type {string}
     * @memberof UserSessionAdminDto
     */
    refreshToken: string;
    /**
     * 
     * @type {string}
     * @memberof UserSessionAdminDto
     */
    tokenType: string;
    /**
     * 
     * @type {number}
     * @memberof UserSessionAdminDto
     */
    expiresIn: number;
    /**
     * 
     * @type {number}
     * @memberof UserSessionAdminDto
     */
    refreshExpiresIn: number;
}

/**
 * Check if a given object implements the UserSessionAdminDto interface.
 */
export function instanceOfUserSessionAdminDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "accessToken" in value;
    isInstance = isInstance && "refreshToken" in value;
    isInstance = isInstance && "tokenType" in value;
    isInstance = isInstance && "expiresIn" in value;
    isInstance = isInstance && "refreshExpiresIn" in value;

    return isInstance;
}

export function UserSessionAdminDtoFromJSON(json: any): UserSessionAdminDto {
    return UserSessionAdminDtoFromJSONTyped(json, false);
}

export function UserSessionAdminDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserSessionAdminDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'accessToken': json['accessToken'],
        'refreshToken': json['refreshToken'],
        'tokenType': json['tokenType'],
        'expiresIn': json['expiresIn'],
        'refreshExpiresIn': json['refreshExpiresIn'],
    };
}

export function UserSessionAdminDtoToJSON(value?: UserSessionAdminDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'accessToken': value.accessToken,
        'refreshToken': value.refreshToken,
        'tokenType': value.tokenType,
        'expiresIn': value.expiresIn,
        'refreshExpiresIn': value.refreshExpiresIn,
    };
}

