/* tslint:disable */
/* eslint-disable */
/**
 * OPENCOURIER-API
 * OpenCourier Backend API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserAdminDto
 */
export interface UserAdminDto {
    /**
     * 
     * @type {string}
     * @memberof UserAdminDto
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof UserAdminDto
     */
    role: UserAdminDtoRoleEnum;
    /**
     * 
     * @type {string}
     * @memberof UserAdminDto
     */
    email: string | null;
}


/**
 * @export
 */
export const UserAdminDtoRoleEnum = {
    Admin: 'ADMIN',
    Courier: 'COURIER',
    Partner: 'PARTNER'
} as const;
export type UserAdminDtoRoleEnum = typeof UserAdminDtoRoleEnum[keyof typeof UserAdminDtoRoleEnum];


/**
 * Check if a given object implements the UserAdminDto interface.
 */
export function instanceOfUserAdminDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "role" in value;
    isInstance = isInstance && "email" in value;

    return isInstance;
}

export function UserAdminDtoFromJSON(json: any): UserAdminDto {
    return UserAdminDtoFromJSONTyped(json, false);
}

export function UserAdminDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserAdminDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'role': json['role'],
        'email': json['email'],
    };
}

export function UserAdminDtoToJSON(value?: UserAdminDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'role': value.role,
        'email': value.email,
    };
}

